### ISSUE TITLE
Feature Request : integra TTS con centro notifiche

### ISSUE THREAD

**Issue by jokerigno** [sdesalve/dss_xiaomi_alarm#1]
Ciao,

come da oggetto che ne pensi di inserire la possibilità di usare il centro notifche di Caio al posto di quello sviluppato?

**Comment by sdesalve** [comment]
Ti basta modificare lo script dss_alarm_script_invia_notifiche per le notifiche Telegram e dss_voice_riproduci_messaggio_tts per i messaggi vocali

Segui la guida di Caio per l'integrazione

**Comment by jokerigno** [comment]
Ciao, scusa nel ritardo della risposta, non avevo attivato le notifiche. 

Si certo potrei farlo localmente, il suggerimento però era di inserirlo qui su github anche per facilitare gli utenti che usano già quel package.

Sempre per lo stesso motivo ho qualche altro suggerimento per te (ovvero modifiche che ho dovuto fare per adattare il tuo package alla mia configurazione):

che ne pensi di creare un !secret per dss_alarm_script_invia_notifiche_telegram_con_keyboard, o meglio per notify.notifiche_telegram?
