### ISSUE TITLE
pending_time deprecated

### ISSUE THREAD

**Issue by fredmassa** [sdesalve/dss_xiaomi_alarm#2]
Hi @sdesalve ,
The attribute pending_time, related to alarm_control_panel, is deprecated (starting from last HA update)... Can you help your folks?

Many thanks ;-)

**Comment by sdesalve** [comment]
https://github.com/sdesalve/dss_xiaomi_alarm/commit/bc212c2bfcf92b6d13b2855cbb0ba1d4039d5fa3
